### ISSUE TITLE
Change the current Logo

### ISSUE THREAD

**Issue by tanvidadu** [shikhar-scs/Track-Your-Tabs#5]
The Logo Design needs to be changed to make it more appropriate with the current functionality of the extension.

**Comment by shikhar-scs** [comment]
Thank you for pointing that, I'll follow it up soon or maybe you can file a PR for the same 👍

**Comment by tanvidadu** [comment]
![d066f98a-52d8-40b5-a4bc-361ef76e843d](https://user-images.githubusercontent.com/29161745/35690125-1560f512-079b-11e8-8ed5-32376038cff7.png)
How about something like this ?

**Comment by shikhar-scs** [comment]
That actually looks pretty good. We'll incorporate this into our project. Please file a PR for the same and include it into the images directory inside the chrome extension directory. Ensure a suitable name. And keep them contributions coming 👍

**Comment by shikhar-scs** [comment]
Closed via #6
